server:
  port: ${SPRING_PORT:8080}
spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:fiap}
    password: ${SPRING_RABBITMQ_PASSWORD:senhafiap}
    connection-timeout: 10000
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 5